services:
  demo-api:
    container_name: demo-api

    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - 8000:8000

    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000